export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const DEL_INGREDIENT: 'DEL_INGREDIENT' = 'DEL_INGREDIENT';
export const SET_INGREDIENT: 'SET_INGREDIENT' = 'SET_INGREDIENT';
export const SET_INGREDIENT_IS_DRAG: 'SET_INGREDIENT_IS_DRAG' = 'SET_INGREDIENT_IS_DRAG';
export const CLEAR_CART: 'CLEAR_CART' = 'CLEAR_CART';