export const OPEN_MODAL: 'OPEN_MODAL' = 'OPEN_MODAL';
export const CLOSE_MODAL: 'CLOSE_MODAL' = 'CLOSE_MODAL';
export const SET_MODAL_TITLE: 'SET_MODAL_TITLE' = 'SET_MODAL_TITLE';
export const SET_MODAL_CONTENT: 'SET_MODAL_CONTENT' = 'SET_MODAL_CONTENT';
export const SET_MODAL_CLOSE_CALLBACK: 'SET_MODAL_CLOSE_CALLBACK' = 'SET_MODAL_CLOSE_CALLBACK';